#!/bin/bash

for i in 1 2 3 4 5 6 7 8 9 10 11 12
do
    #convert -crop 700x359+20+268 -brightness-contrast -40x-40 original/$i.png $i.png
    convert -crop 700x359+20+268 original/$i.png $i.png
done
convert -crop 700x359+32+268 original/13.png 13.png