#!/bin/bash

for i in 1 2 3 4 5 6 7 8 9 11 12 13 14
do
    #convert -crop 700x359+20+268 -brightness-contrast -40x-40 original/$i.png $i.png
    convert -crop 700x359+366+279 original/$i.png $i.png
done

convert -crop 700x359+335+279 original/10.png 10.png
